### ISSUE TITLE
Remove Carbon Fields

### ISSUE THREAD

**Issue by edjeavons** [eighteen73/orbit#5]
Ideally this plugin would not have a dependency like Carbon Fields. We need to ensure that removing it doesn't spoil usability though.

**Comment by brettsmason** [comment]
@edjeavons I've pushed up some code to the develop branch. Would you mind taking a look when you get a chance?
Ideally in the future we could do with writing a small drop in class for handling duplication across all our plugins, but for now this should remove the dependency.

**Comment by edjeavons** [comment]
I've taken a look (and made a few amends) and it looks good to me. 

We will need to consider the few sites that have already used it before merging into main because some setting names have changes and there's a chance they were utilising Orbit's Carbon Fields elsewhere in the project. It's so few sites that I we can manually update their settings when the new Orbit version is applied.

**Comment by edjeavons** [comment]
All good now apart from the logo upload. Once that's done we'll merge into `main`.
